# Directs the Travis CI build service for WorldWind Java
# For more information see https://docs.travis-ci.com/user/customizing-the-build/

# Set up to run the Java build script per the Travis CI documentation
language: java

# Configure the build to using the minimum and the latest Oracle JDKs and Open JDKs
jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
  - oraclejdk8
  - oraclejdk11
  - oraclejdk-ea

# Install the Ant JUnit package, which is missing from the Travis CI environment. See the Travis documentation: https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages
addons:
  apt:
    packages:
      - ant-optional

# Use xvfb to run tests that require a GUI and give it some time to start
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3

# Build the project
script:
  - ant build

# Deploy develop branch javadocs to gh_pages, and create and deploy CHANGELOG.md on tags
deploy:
  # Publish API documentation to GitHub Pages
  - provider: pages
    github_token: $GITHUB_API_KEY
    local_dir: build/doc/javadoc
    skip_cleanup: true
    on:
      branch: develop
  # Create CHANGELOG.md in the current directory
  - provider: script
    script: ./travis/changelog.sh >> CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true
  # Create a GitHub release and publish CHANGELOG.md to the release assets
  - provider: releases
    api_key: $GITHUB_API_KEY
    file: CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true
